modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/team-abnormals/berry-good/issues"
license = "https://github.com/team-abnormals/berry-good/blob/main/LICENSE.txt"

[[mods]]
    modId = "berry_good"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "berry_good:sweet_berry_pips"
    configBackground = "minecraft:textures/block/spruce_log.png"
    authors = "Team Abnormals"
    credits = "SmellyModder, Cameron, five, bageldotjpg"
    displayURL = "https://www.teamabnormals.com/mods/berry-good"
    displayName = "Berry Good"
    description = '''
    Makes sweet berries less annoying to eat and adds more berry related content
    '''

[[dependencies.berry_good]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.berry_good]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.berry_good]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.0,)"
    ordering = "AFTER"
    side = "BOTH"